language: php

php:
  - 7.2
  - nightly

services:
  - postgresql

install:
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - psql -c 'create database hotelmanager;' -U postgres
  - cp .env.travis .env
  - php artisan key:generate --force
  - php artisan migrate --force

script:
  - vendor/bin/phpunit