version: "3.6"

volumes:
  # postgres-data
  postgres-data:
    driver: local
  # redis-data
  redis-data:
    driver: local
  # dot-config
  dot-config:
    driver: local
  # dot-cache
  dot-cache:
    driver: local
  # dot-local
  dot-local:
    driver: local
  # dot-composer
  dot-composer:
    driver: local

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hotelmanager
      - POSTGRES_USER=hotelmanager_user
      - POSTGRES_PASSWORD=hotelmanager_pass

  cache:
    image: redis:5.0-alpine
    command: --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  web:
    image: ambientum/php:7.3-nginx
    volumes:
      - .:/var/www/app
      - dot-config:/home/ambientum/.config
      - dot-cache:/home/ambientum/.cache
      - dot-local:/home/ambientum/.local
      - dot-composer:/home/ambientum/.composer
    environment:
      - FRAMEWORK=laravel
      - XDEBUG_ENABLED=true
      - OPCACHE_MODE=normal
      - PHP_MEMORY_LIMIT=256M
    ports:
      - target: 8080
        published: 8080
      - target: 8083
        published: 8083
    links:
      - postgres
      - cache

  queue:
    image: ambientum/php:7.3
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - postgres
      - cache
