version: '3.4'

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

services:
  postgres:
    image: postgres:11
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hotelmanager
      - POSTGRES_USER=hotelmanager_user
      - POSTGRES_PASSWORD=hotelmanager_pass

  cache:
    image: redis:5.0-alpine
    command: --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  app:
    image: ambientum/php:7.3-nginx
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
      - cache

  queue:
    image: ambientum/php:7.3
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - postgres
      - cache
